source-file ~/.tmux/00-base.conf
source-file ~/.tmux/10-theme.conf
source-file ~/.tmux/20-keybinds.conf
source-file ~/.tmux/30-plugins.conf

# --- 端末ごとにコメント解除 ---
source-file ~/.tmux/40-copy-paste-wayland.conf   # Wayland + wl-clipboard
