[taiki06242005@gmail.com]
source = imaps://taiki06242005%40gmail.com@imap.gmail.com:993
outgoing = smtps://taiki06242005%40gmail.com@smtp.gmail.com:465
source-cred-cmd = echo sbgc wfup cmwl tmxc
outgoing-cred-cmd = echo sbgc wfup cmwl tmxc
default = INBOX
from = Taiki <taiki06242005@gmail.com>
copy-to = Sent

[k24rs122@gmail.com]
source = imaps://k24rs122%40gmail.com@imap.gmail.com:993
outgoing = smtps://k24rs122%40gmail.com@smtp.gmail.com:465
source-cred-cmd = echo iwym gpqp ttqe ycsg
outgoing-cred-cmd = echo iwym gpqp ttqe ycsg
default = INBOX
from = k24rs122 <k24rs122@gmail.com>
copy-to = Sent
