# X11 + xclip 用クリップボード
setw -g mode-keys vi
bind-key -T copy-mode-vi Enter send-keys -X cancel
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "xclip -selection clipboard"
unbind-key -T root MouseDown3Pane
unbind-key -T root M-MouseDown3Pane
bind-key -n MouseDown3Pane run-shell "~/.tmux/paste.sh"
bind-key -n S-MouseDown3Pane run-shell "~/.tmux/paste.sh"
bind-key -n M-MouseDown3Pane display-menu -T "#[align=centre]#{pane_index}" -t = -x M -y M "Split H" h { split-window -h } "Split V" v { split-window -v } "Kill" X { kill-pane } "Zoom" z { resize-pane -Z }
