# macOS 標準クリップボード（追加パッケージ不要）
set -g set-clipboard on
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "pbcopy"
bind-key -n MouseDown3Pane run-shell "~/.tmux/paste.sh"
bind-key -n S-MouseDown3Pane run-shell "~/.tmux/paste.sh"
